### ISSUE TITLE
Install on High Sierra creates .bash_profile?

### ISSUE THREAD

**Issue by theBlbDan** [fabriziocucci/git-bash-for-mac#1] opened 2018-01-31 23:47 UTC
I didn't take the time to investigate this, but it appears that when I try to install this on High Sierra, some sed script gets confused and creates the .bash_profile with an ending '?' in the name of the file.

I assume it is High sierra because it wasn't until I used your installer there that I ran into this problem.

**Comment by fabriziocucci** [comment] 2018-02-02 19:31
Hey @theBlbDan, thanks for reporting this and apologies for my late reply.

That looks a bit suspicious, I've installed the script on my mac with macOS High Sierra only a few weeks ago and I haven't noticed anything unusual.

Could you please try to rename back the `.bash_profile?` in your user directory, go through the uninstall procedure followed by the install procedure?

**Comment by fabriziocucci** [comment] 2018-02-14 18:34
@theBlbDan 
I'm closing this since I wasn't able to reproduce it, please feel free to re-open it if you can help me figure out what happened in your case.

**Closed as completed by fabriziocucci** 2018-02-14 18:34 UTC
