### ISSUE TITLE
cannot uninstall git bash for mac

### ISSUE THREAD

**Issue by RustemAqtau** [fabriziocucci/git-bash-for-mac#2] opened 2018-06-28 01:13 UTC
I have a problem after several unsuccessful running install/uninstall commands and terminal displays this words: 
Last login: Thu Jun 28 06:07:27 on ttys000
-bash: export: `/Users/userName/.git-bash-for-mac.sh': not a valid identifier

**Comment by fabriziocucci** [comment] 2018-06-28 07:25
Hi @RustemAqtau,

please try to open the file `~/.bash_profile` with a text editor and manually remove the line:

```
source ~/.git-bash-for-mac.sh
```

After doing that, close all `Terminal` instances by doing `Terminal` -> `Quit Terminal`.

If that succeeds, we can give a try together to re-install it. If you could report here the issue you were experiencing after running the install procedure it would be really helpful.

**Comment by fabriziocucci** [comment] 2018-08-18 13:19
@RustemAqtau 
I'm closing this since I wasn't able to reproduce it, please feel free to re-open it if you can help me figure out what happened in your case.

**Closed as completed by fabriziocucci** 2018-08-18 13:19 UTC
